/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_TemperatureMeter
#define HEADER_TemperatureMeter
/*
htop - TemperaterMeter.h
*/

#include "Meter.h"

extern int TemperatureMeter_attributes[];

extern MeterClass TemperatureMeter_class;

#endif
